using System;
namespace Dangl.ClockodoExport
{
#pragma warning disable CS1591 // Missing XML comment for publicly visible type or member
    // This file is automatically generated
    [System.CodeDom.Compiler.GeneratedCode("GitVersionBuild", "")]
    public static class VersionInfo
    {
        public static string Version => "0.1.2-beta0002";
        public static string CommitInfo => "Branch.develop.Sha.f27890cbab2c87b15ab04d0be2851f20f89becc2";
        public static string CommitDate => "2021-01-02";
        public static string CommitHash => "f27890cbab2c87b15ab04d0be2851f20f89becc2";
        public static string InformationalVersion => "0.1.2-beta.2+Branch.develop.Sha.f27890cbab2c87b15ab04d0be2851f20f89becc2";
        public static DateTime BuildDateUtc => new DateTime(2021, 1, 2, 19, 5, 0, DateTimeKind.Utc);
    }
}